name: tbs_grade_calculator
description: A new Flutter project.
publish_to: 'none'
version: 0.2.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  package_info_plus: ^5.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
