name: tbs_grade_calculator
description: The TBS Grade Calculator is a student-built app for calculating grades, GPAs, and sharing results. Built with a focus on usability and sharing, it empowers students to manage their academic progress collaboratively.  Open-sourced & community-driven.
publish_to: 'none'
version: 1.3.4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
